apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  labels:
    app: ollama
  namespace: ollama
spec:
  selector:
    matchLabels:
      app: ollama # has to match .spec.template.metadata.labels
  serviceName: ollama
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: ollama # has to match .spec.selector.matchLabels
    spec:
      initContainers:
        - name: pull
          image: quay.io/flysangel/ollama/ollama:latest
          command:
            - bash
            - -c
            - |
              ollama serve &
              sleep 5 # wait ollama server
              for model in echo $(echo ${PULL_MODELS} | tr ',' ' '); do
                ollama list | grep -q ${model} || \
                  ollama pull ${model}
              done
          env:
            - name: PULL_MODELS
              value: "llama3.2:1b,nomic-embed-text"
          volumeMounts:
            - name: ollama
              mountPath: /root/.ollama
      containers:
        - name: ollama
          image: quay.io/flysangel/ollama/ollama:latest
          imagePullPolicy: Always # Always, Nerver, IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: ollama
              mountPath: /root/.ollama
  volumeClaimTemplates:
    - metadata:
        name: ollama
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
