apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webui
  namespace: ollama
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
