apiVersion: v1
kind: Service
metadata:
  name: webui
  labels:
    app: webui
  namespace: ollama
spec:
  selector:
    app: webui
  ports:
    - port: 3000
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
